### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Exarchh** [TheDutchMC04/HaroTorch#1]
**Describe the bug**
Console exception spam.

**To Reproduce**
I only added the plugin to the plugins folder and restarted the server.

**Expected behavior**
Previous versions didn't show this error nor did it spam my console/logs.

**Screenshots**
![image](https://user-images.githubusercontent.com/55347392/99038145-2becc400-25d9-11eb-96c9-dab782b7e890.png)

**Version**
Minecraft version: 1.16.4
Spigot/Paper/Bukkit version [/version]: Paper-261
HaroTorch version: HaroTorch 2.1.5

**Additional context**
N/A

**Comment by TobiasDeBruijn** [comment]
I can't reproduce this on my end. Did you upgrade from 1.x?

Could you please run the attached JAR, and send the debug output on a pastebin link? (Had to zip up the file, GitHub doesn't allow jars here)

[HaroTorch-2.1.5-DEV.jar.zip](https://github.com/TheDutchMC/HaroTorch/files/5535666/HaroTorch-2.1.5-DEV.jar.zip)

**Comment by Exarchh** [comment]
Do you mean a server debug or is there a HT command I am unaware of?

**Comment by TobiasDeBruijn** [comment]
The jar that is in the zip file of my previous comment has some more debugging things enabled, so when you place a torch it should write a lot of information to the console, all starting with [DEBUG]. That is the information I need :)

**Comment by Exarchh** [comment]
Ohh, the plugin works perfectly fine haha, it just spams the console with
the exception message I liked in this report and I don’t have a clue why.

**Comment by TobiasDeBruijn** [comment]
Neither do I, that is why I want to get to the bottom of it ^_^

But glad the plugin still works as expected, which I find surprising as the error is a NullPointerException :)

**Comment by Exarchh** [comment]
https://pastebin.com/FN8if4pP

**Comment by TobiasDeBruijn** [comment]
Okay I've been doing some thinking, since I don't really get why the issue occurs since nothing is null. But I might have come up with a solution.

Could you try this one for me?
[HaroTorch-2.1.5-DEV-rev-2.jar.zip](https://github.com/TheDutchMC/HaroTorch/files/5542710/HaroTorch-2.1.5-DEV-rev-2.jar.zip)

Thanks!

**Comment by Exarchh** [comment]
With that jar, there's no errors and console spam apart from the debug reports

**Comment by TobiasDeBruijn** [comment]
Awesome! Ill create a version 2.1.6 then, that will remove the spam. This can then be found [here](https://github.com/TheDutchMC/HaroTorch/releases)
