### ISSUE TITLE
[Feature] Cooldown between command execution

### ISSUE THREAD

**Issue by Uboaaaaa** [TheDutchMC04/HaroTorch#10]
**Is your feature request related to a problem? Please describe.**
Naughty players can spam /torch aoe and spawn tremendous amount of particles around them

**Describe the solution you'd like**
Add a cooldown to /torch aoe and /torch highlight?

**Describe alternatives you've considered**
Send packet to the player rather than actually spawning the particle?

**Additional context**
![image](https://user-images.githubusercontent.com/70588463/119642945-25a29480-be13-11eb-916f-3f0a15124ed2.png)
![image](https://user-images.githubusercontent.com/70588463/119642884-191e3c00-be13-11eb-8980-35428bf6b370.png)

**Comment by TobiasDeBruijn** [comment]
I've implemented both your suggestion, and your considered alternative :D
![image](https://user-images.githubusercontent.com/28569170/119718713-30d3df80-be68-11eb-8423-0b4ea94f0d62.png)

I'll create a release in a bit, the update instructions will be there then too.
Thanks for reporting!

**Comment by TobiasDeBruijn** [comment]
Apologies for the commit mayhem there, ignore everything but the last one.

**Comment by TobiasDeBruijn** [comment]
v2.3.0 has now been released on spigotmc.org :)
