### ISSUE TITLE
[BUG] Trapdoor breaks torch

### ISSUE THREAD

**Issue by Uboaaaaa** [TheDutchMC04/HaroTorch#11]
**Describe the bug**
If the material used for Haro torch is a torch/lantern, and it is placed on top of a trapdoor, it will be broken the moment the trapdoor is opened, leaving floating particles.

**To Reproduce**
1. Place a trapdoor (top)
2. Place a haro torch on top of the trapdoor
3. Flip the trapdoor.

**Expected behavior**
- Unable to flip trapdoors underneath a Harotorch, or
- Plugin removes the torch and drops the item once the trapdoor is opened, or
- Unable to put Harotorch on trapdoors

**Screenshots**
![image](https://user-images.githubusercontent.com/70588463/120793112-6777bd00-c52e-11eb-9ffb-28399ed6d3a2.png)

**Version**
Minecraft version: 1.16.5
HaroTorch version: 2.3.0

**Comment by TobiasDeBruijn** [comment]
v2.3.1 includes this fix :)
