### ISSUE TITLE
[Feature] Block Blacklist in which the torch can't be placed on.

### ISSUE THREAD

**Issue by Uboaaaaa** [TheDutchMC04/HaroTorch#12]
**Is your feature request related to a problem? Please describe.**
Another issue relating to torch breaking.... **Scaffolding**. I use soul lantern as my block material for the torch which can be placed on scaffolding blocks. When someone placed it on top of a scaffolding block, then break the ones below it, the tower breaks alongside the lantern, once again leaving a "ghost torch" behind.

**Describe the solution you'd like**
Add a block blacklist which can be used to restrict the placement of Haro torches? This way we can stop it from being placed on blocks that's "vulnerable". In this case scaffolding, but may also be trapdoors, pistons, dispensers etc.

**Comment by TobiasDeBruijn** [comment]
That's one edge case I didn't think of!

I should be able to fix this, and add a blacklist somewhere next week!
