### ISSUE TITLE
[Feature] Spawn bloacker height control

### ISSUE THREAD

**Issue by fnrcum** [TheDutchMC04/HaroTorch#13]
**Is your feature request related to a problem? Please describe.**
Based on the current implementation, it is not possible to decide the `Y` values for the spawn blocking. 

**Describe the solution you'd like**
The solution is to tweak the math formula to take into account a `Y` variable formed of 2 values. 
First value would be the height to reach to from the placed position
Second value would be the below range it should have from the placed position

**Describe alternatives you've considered**
Another interesting alternative would be to give it an ingame interface. For example after you place the torch down, if you right click on it, you get a menu in which you can control the range of X=Z and Y+/Y- values up to a maximum decided in the config. This would give the Torch an even greater ingame value for player made builds that do not want mobs spawning in areas where they also don't want visible light.
It could also have a option for server operators to bypass the range limitations in the config.

**Additional context**
I know you can use world guard to set "no mob spawn" zones but some of us prefer having items placed in cities that shows a player that the "city" uses the same(ish) rules.

**Comment by TobiasDeBruijn** [comment]
I think this can be closed now
