### ISSUE TITLE
[BUG] Server stops responding when using /torch aoe

### ISSUE THREAD

**Issue by cilerba** [TheDutchMC04/HaroTorch#15]
**Describe the bug**
The server stops responding when a player uses /torch aoe, server thread dump below

**Version**
Minecraft version: 1.17
Spigot/Paper/Bukkit version [/version]: Paper 1.17-75
HaroTorch version: 2.4.0

List of Plugins:
ChatColorPlus 2.6
LuckPerms 5.3.47
MoreMobHeads 1.15_1.0.21
ProtocolLib
rightClickHarvest

**Additional context**
Server thread dump:
https://pastebin.com/gDCRWRw0

**Comment by TobiasDeBruijn** [comment]
Hm, I thought I fixed this. Will see what I can do!
