### ISSUE TITLE
Config to filter mob types[Feature]

### ISSUE THREAD

**Issue by TerdyTheTerd** [TheDutchMC04/HaroTorch#2]
**Describe the solution you'd like**
It seems that currently the torch blocks all mob spawning. I would like to see a config so that I can specify either a whitelist or blacklist of mob types to allow/prevent. In my use case I want to prevent hostile mob types from spawning, but nothing else, and I still want passive mobs spawning.

**Comment by TobiasDeBruijn** [comment]
I like that idea!

When I have some more spare time I'll definitely take the time to implement this, along with a config option to only prevent hostile mobs

**Comment by TobiasDeBruijn** [comment]
Added in v2.2.0
