### ISSUE TITLE
[Feature] Add config to let non owners break the torches

### ISSUE THREAD

**Issue by TerdyTheTerd** [TheDutchMC04/HaroTorch#3]
**Describe the solution you'd like**
Running a factions server, it is very annoying for players who cannot break the torches that someone else in their faction placed. I would like to see a config option to enable anyone to break the torches, so that people in the same faction don't have to wait for the torches owner to log in to remove it.

**Comment by TobiasDeBruijn** [comment]
Added to the list!

I think I should be able to get an update out this week, including your other suggestion

**Comment by TerdyTheTerd** [comment]
Awesome! In the meantime I had forked and compiled a custom version where anyone can break the torches, as it was really becoming an issue on my factions server. Can't wait for the official changes so I can limit mob types as well :D

**Comment by TobiasDeBruijn** [comment]
Added in v2.2.0
