### ISSUE TITLE
Cannot load with Java 8

### ISSUE THREAD

**Issue by TerdyTheTerd** [TheDutchMC04/HaroTorch#4]
I love the new changes, but it appears you compiled with a new Java version, as the plugin cannot load with Java 8 latest version. Since minecraft still targets Java 8 support, it might be a good idea to recompile it with this version to avoid users running into compatibility issues with newer java issues.

**Comment by TobiasDeBruijn** [comment]
Thats....odd. which version of spigot are you using?

I tested with the latest 1.16.4, which ran just fine with Java 11, have you tried installing Java 11, since Minecraft is not locked to Java 8 and can work with 11 😃

**Comment by TobiasDeBruijn** [comment]
Java 8 jar is now available [here](https://github.com/TheDutchMC/HaroTorch/releases/tag/2.2.0-9)
