### ISSUE TITLE
[BUG] Torch doesn't block Magma Cubes and Ghasts from spawning

### ISSUE THREAD

**Issue by Uboaaaaa** [TheDutchMC04/HaroTorch#5]
**Describe the bug**
Haro torch doesn't seem to prevent Magma Cubes and Ghasts from spawning, even if they're not enlisted in the whitelist.

**To Reproduce**
Place down a harotorch.
Try spawning a Ghast or Magma cube around it.

**Expected behavior**
The two monster being blocked from spawning

**Version**
Minecraft version: 1.16.5
Spigot/Paper/Bukkit version [/version]: Tested on git-Paper-642 and git-Yatopia-103.
HaroTorch version: 2.2.0

**Comment by TobiasDeBruijn** [comment]
Hm That is definitely interesting. Ill see what I can do about this!

**Comment by TobiasDeBruijn** [comment]
It'll be live in v2.2.1. Thanks for reporting!
