### ISSUE TITLE
[Feature] Maximum torch per player

### ISSUE THREAD

**Issue by Uboaaaaa** [TheDutchMC04/HaroTorch#6]
I installed the plugin for my server so builders can create a gloomy atmosphere without having to be worried about mob spawning. However, recently players managed to farm the materials that's used to craft the torch, and was planning to spawn-proof areas using hundreds of torches so that they can get their mob farms to work at highest efficiency. This is against my original intention and I'm rather worried about the server's performance with so many Harotorches placed down together.

Could you please, add a configurable cap over the amount of torches per player can have in the world? And possibly a permission to bypass it?

**Comment by TobiasDeBruijn** [comment]
Yep that is definitely possible! I'll see if I'm able to find a spot of free time today to implement it!

**Comment by TobiasDeBruijn** [comment]
To add the limits you'll have to modify two files, `config.yml` and `en.properties`:

in `config.yml` add:
```yaml
# How many torches are players allowed to place down
# Set to -1 to disable
torchPlaceLimit: 5
```

in `en.properties` under the comment `#PlaceEvent` add:
```properties
torchLimitReached=You have reached the limit of torches you are allowed to place down! You have placed %PLACED_TORCHES%/%TORCH_LIMIT% torches!
```
