### ISSUE TITLE
[BUG] Destroying others' torch by pistoning the block underneath

### ISSUE THREAD

**Issue by Uboaaaaa** [TheDutchMC04/HaroTorch#7]
**Describe the bug**
Players showed this bug to me in which they can destroy other people's Haro torch by moving the block underneath it using a piston.
When the torch (lantern in this case) is destroyed, it drops as normal item, and the particles remain. By placing another lantern at its spot they manage to "claim ownership" of this torch.

**To Reproduce**
1. Place a HaroTorch on a block.
2. Place a piston next to the block.
3. Activiate the piston, the block is moved and the torch drops as an ordinary item.
4. Place a normal torch at its original position.

**Video**
https://youtu.be/EebfILa6JNc

**Version**
Minecraft version: 1.16.5
HaroTorch version: 2.2.0  _(sorry it's not exactly the latest)_
NMS version: v1_16_R3

**Additional context**
It's not a huge problem for my server as we don't rely on claim blocks and stuff at first place. But I think it's still better to report it.

**Comment by TobiasDeBruijn** [comment]
That is one I didnt think about! Thanks for reporting!

It should be a relatively easy fix, I hope!
