### ISSUE TITLE
[BUG] /torch aoe doesn't visualize the effect area in the nether

### ISSUE THREAD

**Issue by Uboaaaaa** [TheDutchMC04/HaroTorch#8]
**Description**
It appears like the plugin tries to display the particles on the topmost layer of the terrain. Nether however is a roofed dimension therefore particles were spawned on top of the nether roof, whereas players usually work underneath it.

**To Reproduce**
1. Go _into_ the nether.
2. Place down a HaroTorch.
3. Run /torch aoe
4. Look for the particle border
5. Ascend onto top of the nether roof and look for the particle border 

**Version**
Minecraft version: 1.16.5
HaroTorch version: 2.2.0

**Comment by TobiasDeBruijn** [comment]
That is interesting...I'll pull v2.2.3 and fix this one then! :"D

**Comment by Uboaaaaa** [comment]
> 
> 
> That is interesting...I'll pull v2.2.3 and fix this one then! :"D

Thank so much for the active support of the plugin （；´д｀）ゞ

**Comment by TobiasDeBruijn** [comment]
> > That is interesting...I'll pull v2.2.3 and fix this one then! :"D
> 
> Thank so much for the active support of the plugin （；´д｀）ゞ

Of course! I use HaroTorch on my own servers as well, so it helps myself too to keep it up-to-date and working ^_^. Besides that I enjoy working on it, something else than my usual work projects is fun too! :"D
